openapi: 3.0.0

info:
  title: E-Commerce API Gateway
  version: 1.0.0

tags:
  - name: Users
  - name: Products
  - name: Orders
  - name: Payments
  - name: Cart
  - name: Reviews

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string

paths:

# ================= USERS =================
  /gateway/users:
    get:
      tags: [Users]
      summary: Get all users
      responses:
        '200': { description: List of users }
        '500': { description: Server error }

    post:
      tags: [Users]
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - firstName
                - lastName
                - email
                - password
                - phone
                - address
                - address.street
                - address.city
                - address.country
                - address.zipCode
              properties:
                id:
                  type: integer
                  minimum: 1   # added
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                phone:
                  type: string
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    zipCode:
                      type: string
                role:
                  type: string
                  enum: [customer, admin]
                  description: |
                    Optional field.
                    If not provided or empty → defaults to "customer".
                    Accepts: customer, Customer, admin, Admin (case-insensitive).
            example:
              id: 1
              firstName: "John"
              lastName: "Doe"
              email: "john@gmail.com"
              password: "123456"
              phone: "+94771234567"
              address:
                street: "123 Main Street"
                city: "Colombo"
                country: "Sri Lanka"
                zipCode: "10100"
              role: "customer"

      responses:
        '201': { description: User created successfully }
        '400':
          description: Missing fields, invalid data types, duplicate user, or invalid role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

  /gateway/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1   # added
      responses:
        '200': { description: User found }
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    put:
      tags: [Users]
      summary: Update user (partial update supported)
      description: |
        Only provided fields will be updated.
        updatedAt will be automatically updated by the system.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1   

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                phone:
                  type: string
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    zipCode:
                      type: string
                role:
                  type: string
                  enum: [customer, admin]
                  description: |
                    Optional field.
                    Accepts: customer, Customer, admin, Admin.
                    Will be normalized to lowercase.
            example:
              firstName: "John Updated"
              lastName: "Doe"
              email: "john@gmail.com"
              password: "123456"
              phone: "+94771234567"
              address:
                street: "123 Main Street"
                city: "Colombo"
                country: "Sri Lanka"
                zipCode: "10100"
              role: "admin"

      responses:
        '200': { description: User updated successfully }
        '400':
          description: Invalid data types or invalid role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    delete:
      tags: [Users]
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1   
      responses:
        '200': { description: User deleted successfully }
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

# ================= PRODUCTS =================
  /gateway/products:
    get:
      tags: [Products]
      summary: Get all products
      responses:
        '200': { description: Product list }
        '500': { description: Server error }

    post:
      tags: [Products]
      summary: Create product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
                - description
                - price
                - category
                - brand
                - stock
              properties:
                id:
                  type: integer
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  minimum: 0
                category:
                  type: string
                brand:
                  type: string
                stock:
                  type: integer
                  minimum: 0
            example:
              id: 1
              name: "iPhone 15"
              description: "Latest Apple smartphone"
              price: 1500
              category: "Electronics"
              brand: "Apple"
              stock: 25
      responses:
        '201': { description: Product created successfully }
        '400':
          description: Missing fields, invalid data types, or duplicate product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

  /gateway/products/{id}:
    get:
      tags: [Products]
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Product found }
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    put:
      tags: [Products]
      summary: Update product (partial update supported)
      description: Only provided fields will be updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  minimum: 0
                category:
                  type: string
                brand:
                  type: string
                stock:
                  type: integer
                  minimum: 0
            example:
              name: "iPhone 15"
              description: "Latest Apple smartphone"
              price: 1500
              category: "Electronics"
              brand: "Apple"
              stock: 25
      responses:
        '200': { description: Product updated successfully }
        '400':
          description: Invalid data types or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    delete:
      tags: [Products]
      summary: Delete product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Product deleted successfully }
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

# ================= ORDERS =================
  /gateway/orders:
    get:
      tags: [Orders]
      summary: Get all orders
      responses:
        '200': { description: List of orders }
        '500': { description: Server error }

    post:
      tags: [Orders]
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
                - items
                - totalAmount
                - orderStatus
                - shippingAddress
              properties:
                id:
                  type: integer

                userId:
                  type: integer

                items:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required:   
                      - productId
                      - quantity
                      - price
                    properties:
                      productId:
                        type: integer
                        description: Product ID must be a number

                      quantity:
                        type: integer
                        minimum: 1
                        description: Must be greater than 0

                      price:
                        type: number
                        minimum: 1
                        description: Must be greater than 0

                totalAmount:
                  type: number
                  minimum: 1

                orderStatus:
                  type: string
                  enum: [pending, confirmed, shipped, delivered, cancelled]

                shippingAddress:
                  type: string

            example:
              id: 1
              userId: 5
              items:
                - productId: 101
                  quantity: 2
                  price: 500
              totalAmount: 1000
              orderStatus: "pending"
              shippingAddress: "Colombo, Sri Lanka"

      responses:
        '201': { description: Order created successfully }
        '400':
          description: Missing fields or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }


  /gateway/orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Order found }
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    put:
      tags: [Orders]
      summary: Update order (partial update supported)
      description: Only provided fields will be updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required:   
                      - productId
                      - quantity
                      - price
                    properties:
                      productId:
                        type: integer

                      quantity:
                        type: integer
                        minimum: 1

                      price:
                        type: number
                        minimum: 1

                totalAmount:
                  type: number
                  minimum: 1

                orderStatus:
                  type: string
                  enum: [pending, confirmed, shipped, delivered, cancelled]

                shippingAddress:
                  type: string

            example:
              items:
                - productId: 101
                  quantity: 3
                  price: 600
              orderStatus: "shipped"

      responses:
        '200': { description: Order updated successfully }
        '400':
          description: Invalid data types or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    delete:
      tags: [Orders]
      summary: Delete order
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Order deleted successfully }
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

# ================= PAYMENTS =================
  /gateway/payments:
    get:
      tags: [Payments]
      summary: Get all payments
      responses:
        '200': { description: Payment list }
        '500': { description: Server error }

    post:
      tags: [Payments]
      summary: Create payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - orderId
                - userId
                - amount
                - currency
                - paymentMethod
                - paymentStatus
              properties:
                id:
                  type: integer
                orderId:
                  type: integer
                userId:
                  type: integer
                amount:
                  type: number
                  minimum: 0
                currency:
                  type: string
                paymentMethod:
                  type: string
                  enum: [card, cash, paypal]
                paymentStatus:
                  type: string
                  enum: [pending, completed, failed]
            example:
              id: 1
              orderId: 1001
              userId: 5
              amount: 500
              currency: "USD"
              paymentMethod: "card"
              paymentStatus: "completed"
      responses:
        '201': { description: Payment created successfully }
        '400':
          description: Missing fields, invalid data types, or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

  /gateway/payments/{id}:
    get:
      tags: [Payments]
      summary: Get payment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Payment found }
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    put:
      tags: [Payments]
      summary: Update payment (partial update supported)
      description: Only provided fields will be updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: integer
                userId:
                  type: integer
                amount:
                  type: number
                  minimum: 0
                currency:
                  type: string
                paymentMethod:
                  type: string
                  enum: [card, cash, paypal]
                paymentStatus:
                  type: string
                  enum: [pending, completed, failed]
            example:
              orderId: 1001
              userId: 5
              amount: 500
              currency: "USD"
              paymentStatus: "failed"
              paymentMethod: "paypal"
      responses:
        '200': { description: Payment updated successfully }
        '400':
          description: Invalid data types or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    delete:
      tags: [Payments]
      summary: Delete payment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Payment deleted successfully }
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }
        
# ================= CART =================
  /gateway/cart:
    get:
      tags: [Cart]
      summary: Get all cart items
      responses:
        '200': { description: Cart items list }
        '500': { description: Server error }

    post:
      tags: [Cart]
      summary: Add to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
                - productId
                - productName
                - quantity
                - price
              properties:
                id:
                  type: integer

                userId:
                  type: integer

                productId:
                  type: integer

                productName:
                  type: string

                quantity:
                  type: integer
                  minimum: 1

                price:
                  type: number
                  minimum: 1

                totalPrice:
                  type: number
                  minimum: 1
                  description: Auto-calculated as quantity × price

            example:
              id: 1
              userId: 5
              productId: 101
              productName: "Laptop"
              quantity: 2
              price: 1200

      responses:
        '201': { description: Item added successfully }
        '400':
          description: Missing fields or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }


  /gateway/cart/{id}:
    get:
      tags: [Cart]
      summary: Get cart item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Cart item found }
        '404':
          description: Cart item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    put:
      tags: [Cart]
      summary: Update cart item (partial update supported)
      description: Only provided fields will be updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productName:
                  type: string

                quantity:
                  type: integer
                  minimum: 1

                price:
                  type: number
                  minimum: 1

            example:
              productName: "Laptop updated"
              quantity: 3
              price: 1300

      responses:
        '200': { description: Cart updated successfully }
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cart item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

    delete:
      tags: [Cart]
      summary: Delete cart item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Cart item deleted successfully }
        '404':
          description: Cart item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': { description: Server error }

# ================= REVIEWS =================
  /gateway/reviews:
    get:
      tags: [Reviews]
      summary: Get all reviews
      responses:
        '200':
          description: Review list
        '500':
          description: Server error

    post:
      tags: [Reviews]
      summary: Create review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
                - productId
                - userName
                - rating
                - verifiedPurchase
              properties:
                id:
                  type: integer

                userId:
                  type: integer

                productId:
                  type: integer

                userName:
                  type: string

                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Rating must be between 1 and 5

                comment:
                  type: string

                verifiedPurchase:
                  type: boolean

            example:
              id: 1
              userId: 5
              productId: 101
              userName: "John Doe"
              rating: 5
              comment: "Excellent product!"
              verifiedPurchase: true

      responses:
        '201':
          description: Review created successfully
        '400':
          description: Missing fields, invalid data types, or rating out of range
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error


  /gateway/reviews/{id}:
    get:
      tags: [Reviews]
      summary: Get review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Review found
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error

    put:
      tags: [Reviews]
      summary: Update review (partial update supported)
      description: |
        Only provided fields will be updated.
        Other fields remain unchanged.

      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string

                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Rating must be between 1 and 5

                comment:
                  type: string

                verifiedPurchase:
                  type: boolean

            example:
              rating: 4
              comment: "Good product!"

      responses:
        '200':
          description: Review updated successfully
        '400':
          description: Invalid data types or rating out of range
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error

    delete:
      tags: [Reviews]
      summary: Delete review
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: Review deleted successfully
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error